# Generated by Django 3.2.16 on 2023-04-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattest',
            name='breeder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='katz.breeder'),
        ),
    ]
